# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='zeroHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xTarget', models.CharField(max_length=30, verbose_name='Target')),
                ('xType', models.CharField(max_length=30, verbose_name='Type')),
                ('xInfo', models.CharField(max_length=10, verbose_name='Info')),
            ],
            options={
                'db_table': 'zeroHistory',
            },
        ),
    ]
